name: SegAttack
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.8.13=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - future=1.0.0=py310h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=75.1=he02047a_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.33.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcap=2.71=h39aace5_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libfabric=2.0.0=ha770c72_1
  - libfabric1=2.0.0=h14e6f36_1
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=hbd13f7d_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.6.4=hb9d3cd8_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_1
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.3=h3dc2cb9_0
  - libudev1=257.3=h9a4d06a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mpi=1.0.1=mpich
  - mpich=4.3.0=h1a8bee6_100
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.10.16=he725a3c_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=5_cp310
  - pyzmq=26.2.1=py310h71f11fc_0
  - rdma-core=56.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - sqlite=3.49.1=h9eae976_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - ucx=1.18.0=hfd9a62f_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.4.0
      - addict==2.4.0
      - adversarial-robustness-toolbox==1.19.1
      - aiofiles==23.2.1
      - albucore==0.0.23
      - albumentations==2.0.5
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - attrs==25.1.0
      - basicsr==1.4.2
      - black==25.1.0
      - boto3==1.38.8
      - botocore==1.38.8
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chumpy==0.70
      - cityscapesscripts==2.2.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - controlnet-aux==0.0.7
      - crcmod==1.7
      - cryptography==44.0.2
      - cycler==0.12.1
      - cython==3.0.2
      - deepspeed==0.13.0
      - detectron2==0.6
      - diffdist==0.1
      - diffuser==0.0.1
      - diffusers==0.32.2 
      - docker-pycreds==0.4.0
      - drjit==1.0.5
      - easydict==1.12
      - einops==0.7.0
      - fastapi==0.115.11
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.14.0
      - filetype==1.2.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - ftfy==6.1.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grad-cam==1.3.9
      - gradio==3.42.0
      - gradio-client==0.5.0
      - graphviz==0.20.3
      - greenlet==3.1.1
      - grpcio==1.70.0
      - h11==0.14.0
      - hf-xet==1.1.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.31.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - infinibatch==0.1.1
      - iopath==0.1.9
      - ipywidgets==8.1.5
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - kornia==0.6.8
      - kornia-rs==0.0.8
      - lazy-loader==0.4
      - llava==0.0.1.dev0
      - llvmlite==0.43.0
      - lmdb==1.6.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mat4py==0.6.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mitsuba==3.6.4
      - mmcv==2.2.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - mmpretrain==1.2.0
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - modelindex==0.0.2
      - more-itertools==10.6.0
      - mpi4py==4.0.3
      - mpmath==1.3.0
      - multiscaledeformableattention==1.0
      - mup==1.0.0
      - mypy-extensions==1.0.0
      - narwhals==1.29.1
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.8.1
      - numba==0.60.0
      - numpy==1.23.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnxruntime==1.21.0
      - openai-whisper==20240930
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - orjson==3.10.15
      - oss2==2.17.0
      - pandas==2.2.3
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pillow==9.4.0
      - pillow-heif==0.22.0
      - plotly==6.0.1
      - pooch==1.8.2
      - portalocker==3.1.1
      - prettytable==3.15.1
      - protobuf==4.25.6
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==13.0.0
      - pybboxes==0.1.6
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pymatting==1.1.13
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.17.0
      - pyquaternion==0.9.9
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytorch-gradcam==0.2.1
      - pytorch3d==0.7.8
      - pytz==2023.4
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - referencing==0.36.2
      - regex==2023.10.3
      - rembg==2.0.64
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.4.2
      - roboflow==1.1.63
      - rpds-py==0.23.1
      - s3transfer==0.12.0
      - safetensors==0.5.3
      - sahi==0.11.22
      - scikit-image==0.21.0
      - scikit-learn==1.3.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - seem==1.0
      - segment-anything==1.0
      - semantic-sam==1.0
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - setuptools==78.1.0
      - shapely==1.8.0
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.39
      - starlette==0.46.0
      - stringzilla==3.12.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tiktoken==0.9.0
      - timm==0.4.12
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - torchviz==0.0.3
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==2.1.0
      - ttach==0.0.3
      - typing==3.7.4.3
      - tzdata==2025.1
      - ultralytics==8.3.85
      - ultralytics-thop==2.0.14
      - urllib3==1.26.20
      - uvicorn==0.34.0
      - visdom==0.2.4
      - vision-datasets==0.2.2
      - wandb==0.15.12
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xformers==0.0.23.post1+cu118
      - yacs==0.1.8
      - yapf==0.43.0
      - yolov5==7.0.14
prefix: /root/miniconda3/envs/SegAttack
